apiVersion: v1
kind: Secret
metadata:
  name: workervotacaosecret
type: Opaque
data:
  UsernameKafka: JENvbm5lY3Rpb25TdHJpbmc=
  PasswordKafka: RW5kcG9pbnQ9c2I6Ly9ncm9mZmVldmVudGh1YnMuc2VydmljZWJ1cy53aW5kb3dzLm5ldC87U2hhcmVkQWNjZXNzS2V5TmFtZT1Xb3JrZXI7U2hhcmVkQWNjZXNzS2V5PWtuaVduS2RXSk12QnRBUnFyYjFKdU1mQ0R6S091RTlFMytBRWhIMFpRZFU9O0VudGl0eVBhdGg9dG9waWMtdm90YWNhbw==
  SaslKafka: cGxhaW50ZXh0
  TlsKafka: ZW5hYmxl